### ISSUE TITLE
running inspect-tools excutables

### ISSUE THREAD

**Issue by jgduenasl** [thegargiulian/inspection-tools#5]
Hi  @thegargiulian , I am trying to use again the scripts in this repo to see into the JEP server some excel files. However, I don't remember if the executables may be run from any place in the directory tree. But it seems I need to make symlinks, how do you run them ?

**Comment by thegargiulian** [comment]
Hi @jgduenasl, after cloning the repo onto my machine, I create symlinks to the scripts in `/bin`. Once you create the symlinks you'll be able to run the commands directly from the command line
